defmodule Mix.Tasks.SootSegments.GenBackfill do
  @shortdoc "Render an INSERT INTO ... SELECT backfill statement for a segment"

  @moduledoc """
  Render an explicit backfill statement that re-aggregates source data
  from `--from` (ISO 8601) into the segment's current target table.

      mix soot_segments.gen_backfill \\
            --out priv/migrations/V0011__backfill_vibration_p95.sql \\
            --segment MyApp.Segments.VibrationP95 \\
            --from 2026-01-01T00:00:00Z

  The backfill is intentionally separate from `gen_migrations`: changing
  a segment definition does NOT silently invalidate historical data, and
  re-aggregating is an operator decision per documented spec.
  """

  use Mix.Task

  @switches [out: :string, segment: :string, from: :string, database: :string]

  @impl Mix.Task
  def run(args) do
    Mix.Task.run("app.start")
    {opts, _} = OptionParser.parse!(args, strict: @switches)

    out = Keyword.fetch!(opts, :out)
    segment_name = Keyword.fetch!(opts, :segment)
    module = Module.concat([segment_name])
    Code.ensure_loaded!(module)

    from =
      case Keyword.get(opts, :from) do
        nil ->
          nil

        iso ->
          {:ok, dt, _} = DateTime.from_iso8601(iso)
          dt
      end

    File.mkdir_p!(Path.dirname(out))

    body =
      "-- Generated by mix soot_segments.gen_backfill\n" <>
        "-- Segment: #{inspect(module)}\n" <>
        "-- From: #{inspect(from)}\n\n" <>
        SootSegments.ClickHouse.DDL.backfill_sql(module, from, opts) <> "\n"

    File.write!(out, body)
    Mix.shell().info("wrote #{out}")
  end
end
