defmodule Mix.Tasks.SootSegments.GenMigrations do
  @shortdoc "Render CREATE TABLE + CREATE MATERIALIZED VIEW for segments"

  @moduledoc """
  Render the ClickHouse migration bundle for one or more segment
  modules.

      mix soot_segments.gen_migrations \\
            --out priv/migrations/V0010__segments.sql \\
            --segment MyApp.Segments.VibrationP95 \\
            --segment MyApp.Segments.PowerDaily \\
            [--database iot]

  Pass `--segment` once per module. The output is a plain `.sql` file
  ready to feed `clickhouse-client`.
  """

  use Mix.Task

  alias SootSegments.{ClickHouse.DDL, Registry}

  @switches [out: :string, segment: [:string, :keep], database: :string]

  @impl Mix.Task
  def run(args) do
    Mix.Task.run("app.start")
    {opts, _} = OptionParser.parse!(args, strict: @switches)

    out = Keyword.fetch!(opts, :out)
    segments = opts |> Keyword.get_values(:segment) |> Enum.map(&load_module/1)

    if segments == [] do
      Mix.raise("at least one --segment <module> is required")
    end

    File.mkdir_p!(Path.dirname(out))

    body =
      "-- Generated by mix soot_segments.gen_migrations\n" <>
        "-- Segments: " <>
        Enum.map_join(segments, ", ", &inspect/1) <>
        "\n\n" <>
        Enum.map_join(segments, "\n\n", &render(&1, opts)) <>
        "\n"

    File.write!(out, body)
    Mix.shell().info("wrote #{out}")
  end

  defp render(module, opts) do
    {:ok, %{segment: segment}} = Registry.register(module)
    DDL.create_view(module, Keyword.put(opts, :target, segment.target))
  end

  defp load_module(name) do
    mod = Module.concat([name])

    case Code.ensure_loaded(mod) do
      {:module, ^mod} -> mod
      {:error, _} -> Mix.raise("could not load #{name} — make sure it's compiled")
    end
  end
end
