defmodule SootSegments.MixTasksTest do
  use ExUnit.Case, async: false

  @tmp Path.join(System.tmp_dir!(), "soot_segments_mix_tasks_test")

  setup do
    File.rm_rf!(@tmp)
    File.mkdir_p!(@tmp)
    on_exit(fn -> File.rm_rf!(@tmp) end)
    :ok
  end

  describe "mix soot_segments.gen_migrations" do
    test "writes a SQL file with CREATE TABLE + CREATE MATERIALIZED VIEW" do
      out = Path.join(@tmp, "0001.sql")

      Mix.Tasks.SootSegments.GenMigrations.run([
        "--out",
        out,
        "--segment",
        "SootSegments.Test.Fixtures.VibrationP95",
        "--segment",
        "SootSegments.Test.Fixtures.PowerDaily"
      ])

      body = File.read!(out)
      assert body =~ "Generated by mix soot_segments.gen_migrations"
      assert body =~ "CREATE TABLE IF NOT EXISTS segment_vibration_p95_v1"
      assert body =~ "CREATE MATERIALIZED VIEW IF NOT EXISTS segment_vibration_p95_v1_mv"
      assert body =~ "CREATE TABLE IF NOT EXISTS segment_power_daily_v1"
    end

    test "errors out without --segment" do
      out = Path.join(@tmp, "x.sql")

      assert_raise Mix.Error, fn ->
        Mix.Tasks.SootSegments.GenMigrations.run(["--out", out])
      end
    end

    test "--database produces fully-qualified table names" do
      out = Path.join(@tmp, "with_db.sql")

      Mix.Tasks.SootSegments.GenMigrations.run([
        "--out",
        out,
        "--database",
        "iot",
        "--segment",
        "SootSegments.Test.Fixtures.VibrationP95"
      ])

      assert File.read!(out) =~ "iot.segment_vibration_p95_v1"
    end
  end

  describe "mix soot_segments.gen_backfill" do
    test "writes an INSERT INTO … SELECT statement with the date floor" do
      out = Path.join(@tmp, "backfill.sql")

      Mix.Tasks.SootSegments.GenBackfill.run([
        "--out",
        out,
        "--segment",
        "SootSegments.Test.Fixtures.VibrationP95",
        "--from",
        "2026-01-01T00:00:00Z"
      ])

      body = File.read!(out)
      assert body =~ "INSERT INTO segment_vibration_p95_v1"
      assert body =~ "FROM telemetry_vibration"
      assert body =~ "ts >= '2026-01-01T00:00:00Z'"
    end
  end
end
